tribal@tribal-XPS-15-7590:~/Desktop/cloud_native_monitoring_application$ pip3 install -r requirements.txt 
Defaulting to user installation because normal site-packages is not writeable
ERROR: Invalid requirement: 'Flask= 2.2.3' (from line 1 of requirements.txt)
Hint: = is not a valid operator. Did you mean == ?
tribal@tribal-XPS-15-7590:~/Desktop/cloud_native_monitoring_application$ pip3 install -r requirements.txt 
Defaulting to user installation because normal site-packages is not writeable
Collecting Flask==2.2.3
  Downloading Flask-2.2.3-py3-none-any.whl (101 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 101.8/101.8 kB 1.4 MB/s eta 0:00:00
Collecting MarkupSafe==2.1.2
  Downloading MarkupSafe-2.1.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (25 kB)
Collecting Werkzeug==2.2.3
  Downloading Werkzeug-2.2.3-py3-none-any.whl (233 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 233.6/233.6 kB 10.1 MB/s eta 0:00:00
Collecting itsdangerous==2.1.2
  Downloading itsdangerous-2.1.2-py3-none-any.whl (15 kB)
Collecting psutil==5.8.0
  Downloading psutil-5.8.0.tar.gz (470 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 470.9/470.9 kB 11.1 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting plotly==5.5.0
  Downloading plotly-5.5.0-py2.py3-none-any.whl (26.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 26.5/26.5 MB 4.4 MB/s eta 0:00:00
Collecting tenacity==8.0.1
  Downloading tenacity-8.0.1-py3-none-any.whl (24 kB)
Collecting boto3==1.9.148
  Downloading boto3-1.9.148-py2.py3-none-any.whl (128 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 128.6/128.6 kB 4.7 MB/s eta 0:00:00
Collecting kubernetes==10.0.1
  Downloading kubernetes-10.0.1-py2.py3-none-any.whl (1.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.5/1.5 MB 4.6 MB/s eta 0:00:00
Requirement already satisfied: click>=8.0 in /usr/lib/python3/dist-packages (from Flask==2.2.3->-r requirements.txt (line 1)) (8.0.3)
Requirement already satisfied: Jinja2>=3.0 in /usr/lib/python3/dist-packages (from Flask==2.2.3->-r requirements.txt (line 1)) (3.0.3)
Requirement already satisfied: six in /usr/lib/python3/dist-packages (from plotly==5.5.0->-r requirements.txt (line 6)) (1.16.0)
Collecting s3transfer<0.3.0,>=0.2.0
  Downloading s3transfer-0.2.1-py2.py3-none-any.whl (70 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 70.2/70.2 kB 6.0 MB/s eta 0:00:00
Collecting jmespath<1.0.0,>=0.7.1
  Downloading jmespath-0.10.0-py2.py3-none-any.whl (24 kB)
Collecting botocore<1.13.0,>=1.12.148
  Downloading botocore-1.12.253-py2.py3-none-any.whl (5.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.7/5.7 MB 6.3 MB/s eta 0:00:00
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='pypi.org', port=443): Read timed out. (read timeout=15)")': /simple/websocket-client/
Collecting websocket-client!=0.40.0,!=0.41.*,!=0.42.*,>=0.32.0
  Downloading websocket_client-1.6.1-py3-none-any.whl (56 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.9/56.9 kB 3.6 MB/s eta 0:00:00
Requirement already satisfied: requests in /usr/lib/python3/dist-packages (from kubernetes==10.0.1->-r requirements.txt (line 9)) (2.27.1)
Requirement already satisfied: urllib3>=1.24.2 in /usr/lib/python3/dist-packages (from kubernetes==10.0.1->-r requirements.txt (line 9)) (1.26.9)
Requirement already satisfied: certifi>=14.05.14 in /usr/lib/python3/dist-packages (from kubernetes==10.0.1->-r requirements.txt (line 9)) (2022.6.15)
Requirement already satisfied: setuptools>=21.0.0 in /usr/lib/python3/dist-packages (from kubernetes==10.0.1->-r requirements.txt (line 9)) (59.6.0)
Requirement already satisfied: python-dateutil>=2.5.3 in /home/tribal/.local/lib/python3.10/site-packages (from kubernetes==10.0.1->-r requirements.txt (line 9)) (2.8.2)
Collecting google-auth>=1.0.1
  Downloading google_auth-2.22.0-py2.py3-none-any.whl (181 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 181.8/181.8 kB 3.9 MB/s eta 0:00:00
Requirement already satisfied: pyyaml>=3.12 in /usr/lib/python3/dist-packages (from kubernetes==10.0.1->-r requirements.txt (line 9)) (5.4.1)
Collecting requests-oauthlib
  Downloading requests_oauthlib-1.3.1-py2.py3-none-any.whl (23 kB)
Collecting urllib3>=1.24.2
  Downloading urllib3-1.25.11-py2.py3-none-any.whl (127 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 128.0/128.0 kB 4.8 MB/s eta 0:00:00
Collecting docutils<0.16,>=0.10
  Downloading docutils-0.15.2-py3-none-any.whl (547 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 547.6/547.6 kB 4.7 MB/s eta 0:00:00
Requirement already satisfied: rsa<5,>=3.1.4 in /usr/lib/python3/dist-packages (from google-auth>=1.0.1->kubernetes==10.0.1->-r requirements.txt (line 9)) (4.8)
Collecting cachetools<6.0,>=2.0.0
  Downloading cachetools-5.3.1-py3-none-any.whl (9.3 kB)
Collecting pyasn1-modules>=0.2.1
  Downloading pyasn1_modules-0.3.0-py2.py3-none-any.whl (181 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 181.3/181.3 kB 5.3 MB/s eta 0:00:00
Requirement already satisfied: oauthlib>=3.0.0 in /usr/lib/python3/dist-packages (from requests-oauthlib->kubernetes==10.0.1->-r requirements.txt (line 9)) (3.2.0)
Requirement already satisfied: pyasn1<0.6.0,>=0.4.6 in /usr/lib/python3/dist-packages (from pyasn1-modules>=0.2.1->google-auth>=1.0.1->kubernetes==10.0.1->-r requirements.txt (line 9)) (0.4.8)
Building wheels for collected packages: psutil
  Building wheel for psutil (setup.py) ... done
  Created wheel for psutil: filename=psutil-5.8.0-cp310-cp310-linux_x86_64.whl size=282546 sha256=4a7cf6d2d78db87f5cab5d302509fb8701b510e9598337206bfdfc9ab6722fe7
  Stored in directory: /home/tribal/.cache/pip/wheels/12/a3/6d/615295409067d58a62a069d30d296d61d3ac132605e3a9555c
Successfully built psutil
Installing collected packages: websocket-client, urllib3, tenacity, requests-oauthlib, pyasn1-modules, psutil, MarkupSafe, jmespath, itsdangerous, docutils, cachetools, Werkzeug, plotly, google-auth, botocore, s3transfer, kubernetes, Flask, boto3
  Attempting uninstall: psutil
    Found existing installation: psutil 5.9.5
    Uninstalling psutil-5.9.5:
      Successfully uninstalled psutil-5.9.5
Successfully installed Flask-2.2.3 MarkupSafe-2.1.2 Werkzeug-2.2.3 boto3-1.9.148 botocore-1.12.253 cachetools-5.3.1 docutils-0.15.2 google-auth-2.22.0 itsdangerous-2.1.2 jmespath-0.10.0 kubernetes-10.0.1 plotly-5.5.0 psutil-5.8.0 pyasn1-modules-0.3.0 requests-oauthlib-1.3.1 s3transfer-0.2.1 tenacity-8.0.1 urllib3-1.25.11 websocket-client-1.6.1
tribal@tribal-XPS-15-7590:~/Desktop/cloud_native_monitoring_application$ python3 app.py
 * Serving Flask app 'app'
 * Debug mode: on
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.1.104:5000
Press CTRL+C to quit
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 145-795-114
127.0.0.1 - - [26/Jul/2023 19:08:05] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [26/Jul/2023 19:08:05] "GET /favicon.ico HTTP/1.1" 404 -
192.168.1.104 - - [26/Jul/2023 19:08:33] "GET / HTTP/1.1" 200 -
192.168.1.104 - - [26/Jul/2023 19:08:33] "GET /favicon.ico HTTP/1.1" 404 -
tribal@tribal-XPS-15-7590:~/Desktop/cloud_native_monitoring_application$ python3 app.py
 * Serving Flask app 'app'
 * Debug mode: on
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.1.104:5000
Press CTRL+C to quit
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 145-795-114
127.0.0.1 - - [26/Jul/2023 19:13:58] "GET / HTTP/1.1" 200 -
192.168.1.104 - - [26/Jul/2023 19:14:11] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [26/Jul/2023 19:19:05] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [26/Jul/2023 19:25:17] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [26/Jul/2023 19:25:24] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [26/Jul/2023 19:26:18] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [26/Jul/2023 19:26:21] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [26/Jul/2023 19:26:21] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [26/Jul/2023 19:26:22] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [26/Jul/2023 19:26:22] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [26/Jul/2023 19:26:22] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [26/Jul/2023 19:26:37] "GET / HTTP/1.1" 200 -
 * Detected change in '/home/tribal/Desktop/cloud_native_monitoring_application/app.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 145-795-114
 * Detected change in '/home/tribal/Desktop/cloud_native_monitoring_application/app.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 145-795-114
127.0.0.1 - - [26/Jul/2023 19:30:00] "GET / HTTP/1.1" 200 -
^Ctribal@tribal-XPS-15-7590:~/Desktop/cloud_native_monitoring_application$ docker build -t my-flask-app .
[+] Building 129.3s (10/10) FINISHED                                                                                                              docker:default
 => [internal] load .dockerignore                                                                                                                           0.1s
 => => transferring context: 2B                                                                                                                             0.0s
 => [internal] load build definition from Dockerfile                                                                                                        0.1s
 => => transferring dockerfile: 226B                                                                                                                        0.0s
 => [internal] load metadata for docker.io/library/python:3.9-buster                                                                                        3.8s
 => [1/5] FROM docker.io/library/python:3.9-buster@sha256:bae5b428ebf32d01a902718b0a58874cbf33d7a4b6a65b7cd7b21d48b0d2e2f1                                 66.5s
 => => resolve docker.io/library/python:3.9-buster@sha256:bae5b428ebf32d01a902718b0a58874cbf33d7a4b6a65b7cd7b21d48b0d2e2f1                                  0.1s
 => => sha256:bae5b428ebf32d01a902718b0a58874cbf33d7a4b6a65b7cd7b21d48b0d2e2f1 988B / 988B                                                                  0.0s
 => => sha256:3b1c264c0ad4598c25048a6dbd3030086cc5c74000e11d04ac27944cb116aabb 17.58MB / 17.58MB                                                           10.0s
 => => sha256:b1e7e053c9f6f57c6d95002167a6d57aed6aacf04dd2f8e681cb4f74a7ca4381 51.87MB / 51.87MB                                                           29.5s
 => => sha256:191a38be55f72871359ebb522ab9621b872e67cac9b4b1834ccf1d2bce3a749d 2.01kB / 2.01kB                                                              0.0s
 => => sha256:2646d4308aee325505bf575b2ecbafb8ef5088d6727585cb6e8215a1534b2472 7.51kB / 7.51kB                                                              0.0s
 => => sha256:ac8bb7e1a32398e26c129ce64e2ddc3e7ec6c34d93424b247f16049f5a91cff4 50.45MB / 50.45MB                                                           18.4s
 => => sha256:a2e1e233599c00054fb839db78b4d42e6f12f36b64280aa62d482a3ad0ad7109 191.88MB / 191.88MB                                                         57.3s
 => => extracting sha256:ac8bb7e1a32398e26c129ce64e2ddc3e7ec6c34d93424b247f16049f5a91cff4                                                                   4.7s
 => => sha256:0ebfe287e9761b9b7dd1703470ff3473a62fe75238f3de01282165f8725968af 6.15MB / 6.15MB                                                             21.9s
 => => sha256:e4e5f05940354b6c226635bb38623cb858415f00f6f856b25d064a5891f887f8 18.00MB / 18.00MB                                                           30.3s
 => => extracting sha256:3b1c264c0ad4598c25048a6dbd3030086cc5c74000e11d04ac27944cb116aabb                                                                   0.6s
 => => sha256:508cf9d1df6776c6d10cd077eb4546b9bf3bb774ed9c6051da6849961ea49fa2 242B / 242B                                                                 30.3s
 => => extracting sha256:b1e7e053c9f6f57c6d95002167a6d57aed6aacf04dd2f8e681cb4f74a7ca4381                                                                   2.5s
 => => sha256:b0eda9c97fd4a2d42571513f0c205e1ae4276f12b3700716064327bdd7a93000 2.85MB / 2.85MB                                                             31.8s
 => => extracting sha256:a2e1e233599c00054fb839db78b4d42e6f12f36b64280aa62d482a3ad0ad7109                                                                   6.4s
 => => extracting sha256:0ebfe287e9761b9b7dd1703470ff3473a62fe75238f3de01282165f8725968af                                                                   0.2s
 => => extracting sha256:e4e5f05940354b6c226635bb38623cb858415f00f6f856b25d064a5891f887f8                                                                   1.0s
 => => extracting sha256:508cf9d1df6776c6d10cd077eb4546b9bf3bb774ed9c6051da6849961ea49fa2                                                                   0.0s
 => => extracting sha256:b0eda9c97fd4a2d42571513f0c205e1ae4276f12b3700716064327bdd7a93000                                                                   0.2s
 => [internal] load build context                                                                                                                           0.1s
 => => transferring context: 3.62kB                                                                                                                         0.0s
 => [2/5] WORKDIR /app                                                                                                                                      0.2s
 => [3/5] COPY requirements.txt .                                                                                                                           0.1s
 => [4/5] RUN pip3 install --no-cache-dir -r requirements.txt                                                                                              50.3s
 => [5/5] COPY . .                                                                                                                                          0.2s
 => exporting to image                                                                                                                                      7.8s
 => => exporting layers                                                                                                                                     7.8s
 => => writing image sha256:148fad8c572040904360bfd89f601315d84acf0d8cda14a9729bb77fa1a571f0                                                                0.0s
 => => naming to docker.io/library/my-flask-app                                                                                                             0.0s
tribal@tribal-XPS-15-7590:~/Desktop/cloud_native_monitoring_application$ docker image

Usage:  docker image COMMAND

Manage images

Commands:
  build       Build an image from a Dockerfile
  history     Show the history of an image
  import      Import the contents from a tarball to create a filesystem image
  inspect     Display detailed information on one or more images
  load        Load an image from a tar archive or STDIN
  ls          List images
  prune       Remove unused images
  pull        Download an image from a registry
  push        Upload an image to a registry
  rm          Remove one or more images
  save        Save one or more images to a tar archive (streamed to STDOUT by default)
  tag         Create a tag TARGET_IMAGE that refers to SOURCE_IMAGE

Run 'docker image COMMAND --help' for more information on a command.
tribal@tribal-XPS-15-7590:~/Desktop/cloud_native_monitoring_application$ docker images
REPOSITORY                    TAG       IMAGE ID       CREATED          SIZE
my-flask-app                  latest    148fad8c5720   49 seconds ago   1.09GB
gcr.io/k8s-minikube/kicbase   v0.0.40   c6cc01e60919   12 days ago      1.19GB
tribal@tribal-XPS-15-7590:~/Desktop/cloud_native_monitoring_application$ docker run -p 5000:5000 148fad8c5720
 * Debug mode: off
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.17.0.2:5000
Press CTRL+C to quit
172.17.0.1 - - [26/Jul/2023 14:13:37] "GET / HTTP/1.1" 200 -
^Ctribal@tribal-XPS-15-7590:~/Desktop/cloud_native_monitoring_application$ python3 ecr.py
Traceback (most recent call last):
  File "/home/tribal/Desktop/cloud_native_monitoring_application/ecr.py", line 1, in <module>
    import boto3
  File "/home/tribal/.local/lib/python3.10/site-packages/boto3/__init__.py", line 16, in <module>
    from boto3.session import Session
  File "/home/tribal/.local/lib/python3.10/site-packages/boto3/session.py", line 17, in <module>
    import botocore.session
  File "/home/tribal/.local/lib/python3.10/site-packages/botocore/session.py", line 29, in <module>
    import botocore.configloader
  File "/home/tribal/.local/lib/python3.10/site-packages/botocore/configloader.py", line 19, in <module>
    from botocore.compat import six
  File "/home/tribal/.local/lib/python3.10/site-packages/botocore/compat.py", line 25, in <module>
    from botocore.exceptions import MD5UnavailableError
  File "/home/tribal/.local/lib/python3.10/site-packages/botocore/exceptions.py", line 15, in <module>
    from botocore.vendored import requests
  File "/home/tribal/.local/lib/python3.10/site-packages/botocore/vendored/requests/__init__.py", line 58, in <module>
    from . import utils
  File "/home/tribal/.local/lib/python3.10/site-packages/botocore/vendored/requests/utils.py", line 26, in <module>
    from .compat import parse_http_list as _parse_list_header
  File "/home/tribal/.local/lib/python3.10/site-packages/botocore/vendored/requests/compat.py", line 7, in <module>
    from .packages import chardet
  File "/home/tribal/.local/lib/python3.10/site-packages/botocore/vendored/requests/packages/__init__.py", line 3, in <module>
    from . import urllib3
  File "/home/tribal/.local/lib/python3.10/site-packages/botocore/vendored/requests/packages/urllib3/__init__.py", line 10, in <module>
    from .connectionpool import (
  File "/home/tribal/.local/lib/python3.10/site-packages/botocore/vendored/requests/packages/urllib3/connectionpool.py", line 38, in <module>
    from .response import HTTPResponse
  File "/home/tribal/.local/lib/python3.10/site-packages/botocore/vendored/requests/packages/urllib3/response.py", line 9, in <module>
    from ._collections import HTTPHeaderDict
  File "/home/tribal/.local/lib/python3.10/site-packages/botocore/vendored/requests/packages/urllib3/_collections.py", line 1, in <module>
    from collections import Mapping, MutableMapping
ImportError: cannot import name 'Mapping' from 'collections' (/usr/lib/python3.10/collections/__init__.py)
tribal@tribal-XPS-15-7590:~/Desktop/cloud_native_monitoring_application$ python3 ecr.py
Traceback (most recent call last):
  File "/home/tribal/Desktop/cloud_native_monitoring_application/ecr.py", line 1, in <module>
    import boto3
  File "/home/tribal/.local/lib/python3.10/site-packages/boto3/__init__.py", line 16, in <module>
    from boto3.session import Session
  File "/home/tribal/.local/lib/python3.10/site-packages/boto3/session.py", line 17, in <module>
    import botocore.session
  File "/home/tribal/.local/lib/python3.10/site-packages/botocore/session.py", line 29, in <module>
    import botocore.configloader
  File "/home/tribal/.local/lib/python3.10/site-packages/botocore/configloader.py", line 19, in <module>
    from botocore.compat import six
  File "/home/tribal/.local/lib/python3.10/site-packages/botocore/compat.py", line 25, in <module>
    from botocore.exceptions import MD5UnavailableError
  File "/home/tribal/.local/lib/python3.10/site-packages/botocore/exceptions.py", line 15, in <module>
    from botocore.vendored import requests
  File "/home/tribal/.local/lib/python3.10/site-packages/botocore/vendored/requests/__init__.py", line 58, in <module>
    from . import utils
  File "/home/tribal/.local/lib/python3.10/site-packages/botocore/vendored/requests/utils.py", line 26, in <module>
    from .compat import parse_http_list as _parse_list_header
  File "/home/tribal/.local/lib/python3.10/site-packages/botocore/vendored/requests/compat.py", line 7, in <module>
    from .packages import chardet
  File "/home/tribal/.local/lib/python3.10/site-packages/botocore/vendored/requests/packages/__init__.py", line 3, in <module>
    from . import urllib3
  File "/home/tribal/.local/lib/python3.10/site-packages/botocore/vendored/requests/packages/urllib3/__init__.py", line 10, in <module>
    from .connectionpool import (
  File "/home/tribal/.local/lib/python3.10/site-packages/botocore/vendored/requests/packages/urllib3/connectionpool.py", line 38, in <module>
    from .response import HTTPResponse
  File "/home/tribal/.local/lib/python3.10/site-packages/botocore/vendored/requests/packages/urllib3/response.py", line 9, in <module>
    from ._collections import HTTPHeaderDict
  File "/home/tribal/.local/lib/python3.10/site-packages/botocore/vendored/requests/packages/urllib3/_collections.py", line 1, in <module>
    from collections import Mapping, MutableMapping
ImportError: cannot import name 'Mapping' from 'collections' (/usr/lib/python3.10/collections/__init__.py)
tribal@tribal-XPS-15-7590:~/Desktop/cloud_native_monitoring_application$ python3 ecr.py
Traceback (most recent call last):
  File "/home/tribal/Desktop/cloud_native_monitoring_application/ecr.py", line 2, in <module>
    import boto3
  File "/home/tribal/.local/lib/python3.10/site-packages/boto3/__init__.py", line 16, in <module>
    from boto3.session import Session
  File "/home/tribal/.local/lib/python3.10/site-packages/boto3/session.py", line 17, in <module>
    import botocore.session
  File "/home/tribal/.local/lib/python3.10/site-packages/botocore/session.py", line 29, in <module>
    import botocore.configloader
  File "/home/tribal/.local/lib/python3.10/site-packages/botocore/configloader.py", line 19, in <module>
    from botocore.compat import six
  File "/home/tribal/.local/lib/python3.10/site-packages/botocore/compat.py", line 25, in <module>
    from botocore.exceptions import MD5UnavailableError
  File "/home/tribal/.local/lib/python3.10/site-packages/botocore/exceptions.py", line 15, in <module>
    from botocore.vendored import requests
  File "/home/tribal/.local/lib/python3.10/site-packages/botocore/vendored/requests/__init__.py", line 58, in <module>
    from . import utils
  File "/home/tribal/.local/lib/python3.10/site-packages/botocore/vendored/requests/utils.py", line 26, in <module>
    from .compat import parse_http_list as _parse_list_header
  File "/home/tribal/.local/lib/python3.10/site-packages/botocore/vendored/requests/compat.py", line 7, in <module>
    from .packages import chardet
  File "/home/tribal/.local/lib/python3.10/site-packages/botocore/vendored/requests/packages/__init__.py", line 3, in <module>
    from . import urllib3
  File "/home/tribal/.local/lib/python3.10/site-packages/botocore/vendored/requests/packages/urllib3/__init__.py", line 10, in <module>
    from .connectionpool import (
  File "/home/tribal/.local/lib/python3.10/site-packages/botocore/vendored/requests/packages/urllib3/connectionpool.py", line 38, in <module>
    from .response import HTTPResponse
  File "/home/tribal/.local/lib/python3.10/site-packages/botocore/vendored/requests/packages/urllib3/response.py", line 9, in <module>
    from ._collections import HTTPHeaderDict
  File "/home/tribal/.local/lib/python3.10/site-packages/botocore/vendored/requests/packages/urllib3/_collections.py", line 1, in <module>
    from collections import Mapping, MutableMapping
ImportError: cannot import name 'Mapping' from 'collections' (/usr/lib/python3.10/collections/__init__.py)
tribal@tribal-XPS-15-7590:~/Desktop/cloud_native_monitoring_application$ python version
Command 'python' not found, did you mean:
  command 'python3' from deb python3
  command 'python' from deb python-is-python3
tribal@tribal-XPS-15-7590:~/Desktop/cloud_native_monitoring_application$ python3 version
python3: can't open file '/home/tribal/Desktop/cloud_native_monitoring_application/version': [Errno 2] No such file or directory
tribal@tribal-XPS-15-7590:~/Desktop/cloud_native_monitoring_application$ python3 --version
Python 3.10.7
tribal@tribal-XPS-15-7590:~/Desktop/cloud_native_monitoring_application$ python3 ecr.py
Traceback (most recent call last):
  File "/home/tribal/Desktop/cloud_native_monitoring_application/ecr.py", line 2, in <module>
    import boto3
  File "/home/tribal/.local/lib/python3.10/site-packages/boto3/__init__.py", line 16, in <module>
    from boto3.session import Session
  File "/home/tribal/.local/lib/python3.10/site-packages/boto3/session.py", line 17, in <module>
    import botocore.session
  File "/home/tribal/.local/lib/python3.10/site-packages/botocore/session.py", line 29, in <module>
    import botocore.configloader
  File "/home/tribal/.local/lib/python3.10/site-packages/botocore/configloader.py", line 19, in <module>
    from botocore.compat import six
  File "/home/tribal/.local/lib/python3.10/site-packages/botocore/compat.py", line 25, in <module>
    from botocore.exceptions import MD5UnavailableError
  File "/home/tribal/.local/lib/python3.10/site-packages/botocore/exceptions.py", line 15, in <module>
    from botocore.vendored import requests
  File "/home/tribal/.local/lib/python3.10/site-packages/botocore/vendored/requests/__init__.py", line 58, in <module>
    from . import utils
  File "/home/tribal/.local/lib/python3.10/site-packages/botocore/vendored/requests/utils.py", line 30, in <module>
    from .cookies import RequestsCookieJar, cookiejar_from_dict
  File "/home/tribal/.local/lib/python3.10/site-packages/botocore/vendored/requests/cookies.py", line 160, in <module>
    class RequestsCookieJar(cookielib.CookieJar, collections.MutableMapping):
AttributeError: module 'collections' has no attribute 'MutableMapping'
tribal@tribal-XPS-15-7590:~/Desktop/cloud_native_monitoring_application$ pip install --upgrade botocore
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: botocore in /home/tribal/.local/lib/python3.10/site-packages (1.12.253)
Collecting botocore
  Downloading botocore-1.31.11-py3-none-any.whl (11.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.0/11.0 MB 2.6 MB/s eta 0:00:00
Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in /home/tribal/.local/lib/python3.10/site-packages (from botocore) (2.8.2)
Requirement already satisfied: urllib3<1.27,>=1.25.4 in /home/tribal/.local/lib/python3.10/site-packages (from botocore) (1.25.11)
Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in /home/tribal/.local/lib/python3.10/site-packages (from botocore) (0.10.0)
Requirement already satisfied: six>=1.5 in /usr/lib/python3/dist-packages (from python-dateutil<3.0.0,>=2.1->botocore) (1.16.0)
Installing collected packages: botocore
  Attempting uninstall: botocore
    Found existing installation: botocore 1.12.253
    Uninstalling botocore-1.12.253:
      Successfully uninstalled botocore-1.12.253
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
boto3 1.9.148 requires botocore<1.13.0,>=1.12.148, but you have botocore 1.31.11 which is incompatible.
Successfully installed botocore-1.31.11
tribal@tribal-XPS-15-7590:~/Desktop/cloud_native_monitoring_application$ python3 ecr.py
033057554021.dkr.ecr.ap-south-1.amazonaws.com/my_monitoring_app_image
tribal@tribal-XPS-15-7590:~/Desktop/cloud_native_monitoring_application$ aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 033057554021.dkr.ecr.ap-south-1.amazonaws.com
WARNING! Your password will be stored unencrypted in /home/tribal/.docker/config.json.
Configure a credential helper to remove this warning. See
https://docs.docker.com/engine/reference/commandline/login/#credentials-store

Login Succeeded
tribal@tribal-XPS-15-7590:~/Desktop/cloud_native_monitoring_application$ docker build -t my_monitoring_app_image .
[+] Building 2.6s (10/10) FINISHED                                                                                                                docker:default
 => [internal] load build definition from Dockerfile                                                                                                        0.1s
 => => transferring dockerfile: 226B                                                                                                                        0.0s
 => [internal] load .dockerignore                                                                                                                           0.0s
 => => transferring context: 2B                                                                                                                             0.0s
 => [internal] load metadata for docker.io/library/python:3.9-buster                                                                                        2.2s
 => [1/5] FROM docker.io/library/python:3.9-buster@sha256:bae5b428ebf32d01a902718b0a58874cbf33d7a4b6a65b7cd7b21d48b0d2e2f1                                  0.0s
 => [internal] load build context                                                                                                                           0.0s
 => => transferring context: 496B                                                                                                                           0.0s
 => CACHED [2/5] WORKDIR /app                                                                                                                               0.0s
 => CACHED [3/5] COPY requirements.txt .                                                                                                                    0.0s
 => CACHED [4/5] RUN pip3 install --no-cache-dir -r requirements.txt                                                                                        0.0s
 => [5/5] COPY . .                                                                                                                                          0.1s
 => exporting to image                                                                                                                                      0.1s
 => => exporting layers                                                                                                                                     0.1s
 => => writing image sha256:ec30ec6a1afce7652ee2447b4fbc0917d02c91ed9c153b793540ff56f65ab7f6                                                                0.0s
 => => naming to docker.io/library/my_monitoring_app_image                                                                                                  0.0s
tribal@tribal-XPS-15-7590:~/Desktop/cloud_native_monitoring_application$ docker tag my_monitoring_app_image:latest 033057554021.dkr.ecr.ap-south-1.amazonaws.com/my_monitoring_app_image:latest
tribal@tribal-XPS-15-7590:~/Desktop/cloud_native_monitoring_application$ docker push 033057554021.dkr.ecr.ap-south-1.amazonaws.com/my_monitoring_app_image:latest
The push refers to repository [033057554021.dkr.ecr.ap-south-1.amazonaws.com/my_monitoring_app_image]
8c55c21daeed: Pushed 
f38d53833d1e: Pushed 
4560ecee049d: Pushed 
d933e21658c6: Pushed 
6708fb287a81: Pushed 
80be4d1ba48b: Pushed 
cc03a41bc194: Pushed 
474c7af10697: Pushed 
dcc1cfeee1ab: Pushed 
eccb9ed74974: Pushed 
53d40515380c: Pushed 
6af7a54a0a0d: Pushed 
latest: digest: sha256:8144db4309eaf013b831a5949b3f19a6617678c5259bee48e0b9a8efec39e8ac size: 2840
tribal@tribal-XPS-15-7590:~/Desktop/cloud_native_monitoring_application$ kubectl get pods -n default
NAME                                                 READY   STATUS    RESTARTS   AGE
grafana-5c59c7f477-46jh9                             1/1     Running   0          3h27m
prometheus-alertmanager-0                            1/1     Running   0          3h36m
prometheus-kube-state-metrics-7fb65d597b-qd88b       1/1     Running   0          3h36m
prometheus-prometheus-node-exporter-j8j4h            1/1     Running   0          3h36m
prometheus-prometheus-pushgateway-79ff799669-fzfgr   1/1     Running   0          3h36m
prometheus-server-5dcccb966d-rtkdq                   2/2     Running   0          3h36m
tribal@tribal-XPS-15-7590:~/Desktop/cloud_native_monitoring_application$ cd .kube/c
bash: cd: .kube/c: No such file or directory
tribal@tribal-XPS-15-7590:~/Desktop/cloud_native_monitoring_application$ python3 eks.py
tribal@tribal-XPS-15-7590:~/Desktop/cloud_native_monitoring_application$ 
